/* Appended to the inherited kernel API fixture; production C is generated by
 * the actual V2 source consumer, with OF facts supplied from the stock FDT. */
int main(int argc,char **argv) {
    assert(argc==2);scenario=argv[1];bat.dev.of_node=&battery;
    for(unsigned i=0;i<S22_THERMAL_SENSOR_COUNT;i++)
        cn[i]=(struct device_node){fixture_sensors[i].name,6,(int)i};
    for(unsigned b=0;b<2;b++) {
        bp[b]=(struct platform_device){.dev={.of_node=&bn[b]},.bank=(int)b};
        resource[b][0]=(struct resource){fixture_resources[b][0],fixture_resources[b][0]+fixture_resources[b][1]-1};
        resource[b][1]=(struct resource){fixture_resources[b][2],fixture_resources[b][2]+fixture_resources[b][3]-1};
        srot_words[b][0]=0x20060000;srot_words[b][1]=1;tm_words[b][0xe4/4]=1;
        for(unsigned i=0;i<16;i++)tm_words[b][0xa0/4+i]=(1U<<21)|(450+b*50+i);
    }
    if(is_case("wrong-model")) {
        assert(thermal_init()==-ENODEV&&!mmio_reads&&!register_calls&&!adc_reads);
        puts("ROOT_REJECTED_BEFORE_REGISTRATION");return 0;
    }
    if(is_case("wrong-map"))map_wrong=1;
    if(is_case("wrong-resource"))resource[0][0].end++;
    if(is_case("wrong-version"))srot_words[0][0]=0x30000000;
    if(is_case("disabled"))srot_words[0][1]=0;
    if(is_case("wrong-table"))table_wrong=1;
    if(is_case("deferred"))provider_missing=1;
    assert(!thermal_init()&&register_calls==1&&!adc_reads);
    assert(sample_ops.get==sample_get&&!sample_ops.set&&diagnostic_ops.get==diagnostic_get&&!diagnostic_ops.set);
    char text[PAGE_SIZE],diag[PAGE_SIZE];unsigned reads=mmio_reads;
    assert(diagnostic_get(diag,NULL)>0&&mmio_reads==reads&&!adc_reads);
    thermal_lock.held=1;assert(sample_get(text,NULL)==-EAGAIN&&!adc_reads);thermal_lock.held=0;
    if(is_case("adc-error"))adc_return=-ETIMEDOUT;
    if(is_case("adc-wrong-format"))adc_return=0;
    if(is_case("adc-zero"))adc_uv=0;
    if(is_case("adc-too-high"))adc_uv=970783;
    if(is_case("negative"))adc_uv=(int)s22_thermal_uv[21];
    if(is_case("partial"))tm_words[1][0xa0/4+4]&=~(1U<<21);
    if(is_case("not-ready"))tm_words[0][0xe4/4]=tm_words[1][0xe4/4]=0;
    if(is_case("runtime-disabled"))srot_words[0][1]=0;
    if(is_case("runtime-version"))srot_words[0][0]=0x30000000;
    if(is_case("cpu-range"))tm_words[0][0xa0/4+5]=(1U<<21)|1501;
    if(is_case("zero") || is_case("no-valid") || is_case("negative"))
        for(unsigned b=0;b<2;b++)for(unsigned i=0;i<16;i++)
            tm_words[b][0xa0/4+i]=is_case("no-valid")?0:(1U<<21)|(is_case("negative")?0xf9c:0);
    int n=sample_get(text,NULL);
    assert(n>0 && n<(int)S22_THERMAL_LINE_CAP && n==(int)strlen(text) && !thermal_lock.held);
    fputs(text,stdout);
    unsigned calls=adc_reads;reads=mmio_reads;
    assert(sample_get(text,NULL)==-EAGAIN&&adc_reads==calls&&mmio_reads==reads);
    assert(diagnostic_get(diag,NULL)>0&&adc_reads==calls&&mmio_reads==reads);
    if(!strncmp(scenario,"adc-",4)) {
        assert(adc_reads==1&&battery_stopped);clock_ms+=10000;
        assert(sample_get(text,NULL)>0&&adc_reads==1);fputs(text,stdout);
    }
    if(is_case("late-bank")) {
        assert(!thermal_probe(&bp[1]));clock_ms+=1000;
        assert(sample_get(text,NULL)>0);fputs(text,stdout);
    }
    if(is_case("deferred")) {
        assert(!adc_reads&&!device_refs&&!channel_refs);provider_missing=0;clock_ms+=1000;
        assert(sample_get(text,NULL)>0&&adc_reads==1);fputs(text,stdout);
    }
    clock_ms=last_start-1;assert(sample_get(text,NULL)==-EOVERFLOW);
    clock_ms=last_start+1000;sequence=U64_MAX;assert(sample_get(text,NULL)==-EOVERFLOW);
    thermal_exit();assert(!device_refs&&!channel_refs&&!banks[0].device&&!banks[1].device);
    return 0;
}
