import json
import struct
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPT_DIR = ROOT / "workspace/public/src/scripts/revalidation"
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

import prepare_nyan_pal8_rle_v2970 as nyan


def write_ppm(path: Path, width: int, height: int, pixels_rgb: bytes, *, comment: bool = False) -> None:
    header = f"P6\n{width} {height}\n255\n".encode("ascii")
    if comment:
        header = f"P6\n# generated by unit test\n{width} {height}\n255\n".encode("ascii")
    path.write_bytes(header + pixels_rgb)


class PrepareNyanPal8RleV2970(unittest.TestCase):
    def test_ppm_sequence_writes_a90vstr2_and_roundtrips_modes(self) -> None:
        with tempfile.TemporaryDirectory(dir=ROOT / "workspace/private/test-runs") as temp:
            root = Path(temp)
            input_dir = root / "frames"
            out_dir = root / "out"
            input_dir.mkdir()
            red = bytes([255, 0, 0])
            blue = bytes([0, 0, 255])
            solid = red * 16
            alternating = b"".join(red if index % 2 == 0 else blue for index in range(16))
            write_ppm(input_dir / "000001.ppm", 8, 2, solid, comment=True)
            write_ppm(input_dir / "000002.ppm", 8, 2, alternating)

            result = nyan.write_stream_from_frames(
                input_dir=input_dir,
                out_dir=out_dir,
                glob_pattern="*.ppm",
                width=8,
                height=2,
                fps_num=30,
                fps_den=1,
                input_format="ppm",
                asset_id="unit-nyan-pal8-rle",
            )

            stream = ROOT / result["stream"]
            data = stream.read_bytes()
            self.assertEqual(data[:8], nyan.MAGIC)
            header = nyan.HEADER_STRUCT.unpack(data[:nyan.HEADER_STRUCT.size])
            self.assertEqual(header[1:8], (nyan.VERSION, 8, 2, 30, 1, 2, 2))
            self.assertGreaterEqual(header[8], 16)
            self.assertEqual(result["mode_counts"], {"pal8-raw": 1, "pal8-rle": 1})
            self.assertEqual(result["encoded_payload_bytes"], 20)
            self.assertEqual(result["raw_pal8_bytes"], 32)

            decoded = nyan.read_stream_for_test(stream)
            self.assertEqual(decoded["modes"], [nyan.MODE_PAL8_RLE, nyan.MODE_PAL8_RAW])
            self.assertEqual(decoded["frames_rgb"], [solid, alternating])

            manifest = json.loads((out_dir / "manifest.json").read_text(encoding="utf-8"))
            self.assertEqual(manifest["asset_id"], "unit-nyan-pal8-rle")
            self.assertEqual(manifest["video"]["format"], "pal8-rle")
            self.assertEqual(manifest["video"]["stream_version"], 2)
            self.assertEqual(manifest["video"]["palette_count"], 2)
            self.assertEqual(manifest["video"]["sha256"], result["sha256"])

    def test_output_hash_is_deterministic(self) -> None:
        with tempfile.TemporaryDirectory(dir=ROOT / "workspace/private/test-runs") as temp:
            root = Path(temp)
            input_dir = root / "frames"
            input_dir.mkdir()
            green = bytes([0, 255, 0])
            yellow = bytes([255, 255, 0])
            write_ppm(input_dir / "000001.ppm", 4, 2, green * 4 + yellow * 4)

            first = nyan.write_stream_from_frames(
                input_dir=input_dir,
                out_dir=root / "out1",
                glob_pattern="*.ppm",
                width=4,
                height=2,
                fps_num=24,
                fps_den=1,
                input_format="ppm",
            )
            second = nyan.write_stream_from_frames(
                input_dir=input_dir,
                out_dir=root / "out2",
                glob_pattern="*.ppm",
                width=4,
                height=2,
                fps_num=24,
                fps_den=1,
                input_format="ppm",
            )
            self.assertEqual(first["sha256"], second["sha256"])

    def test_rejects_more_than_256_palette_colors(self) -> None:
        with tempfile.TemporaryDirectory(dir=ROOT / "workspace/private/test-runs") as temp:
            root = Path(temp)
            input_dir = root / "frames"
            input_dir.mkdir()
            pixels = bytearray()
            for color_index in range(257):
                pixels.extend((color_index & 0xFF, (color_index >> 1) & 0xFF, (color_index >> 2) & 0xFF))
            write_ppm(input_dir / "000001.ppm", 257, 1, bytes(pixels))

            with self.assertRaisesRegex(ValueError, "palette exceeds 256"):
                nyan.write_stream_from_frames(
                    input_dir=input_dir,
                    out_dir=root / "out",
                    glob_pattern="*.ppm",
                    width=257,
                    height=1,
                    fps_num=30,
                    fps_den=1,
                    input_format="ppm",
                )

    def test_rejects_geometry_mismatch(self) -> None:
        with tempfile.TemporaryDirectory(dir=ROOT / "workspace/private/test-runs") as temp:
            root = Path(temp)
            input_dir = root / "frames"
            input_dir.mkdir()
            write_ppm(input_dir / "000001.ppm", 2, 2, bytes([0, 0, 0]) * 4)

            with self.assertRaisesRegex(ValueError, "geometry"):
                nyan.write_stream_from_frames(
                    input_dir=input_dir,
                    out_dir=root / "out",
                    glob_pattern="*.ppm",
                    width=3,
                    height=2,
                    fps_num=30,
                    fps_den=1,
                    input_format="ppm",
                )

    def test_raw_rgb24_input_and_record_layout(self) -> None:
        with tempfile.TemporaryDirectory(dir=ROOT / "workspace/private/test-runs") as temp:
            root = Path(temp)
            input_dir = root / "frames"
            out_dir = root / "out"
            input_dir.mkdir()
            black = bytes([0, 0, 0])
            white = bytes([255, 255, 255])
            (input_dir / "frame.rgb").write_bytes(black * 4 + white * 4)

            result = nyan.write_stream_from_frames(
                input_dir=input_dir,
                out_dir=out_dir,
                glob_pattern="*.rgb",
                width=4,
                height=2,
                fps_num=12,
                fps_den=1,
                input_format="raw-rgb24",
            )

            data = (ROOT / result["stream"]).read_bytes()
            palette_offset = nyan.HEADER_STRUCT.size
            record_offset = palette_offset + 2 * 4
            record = nyan.FRAME_RECORD_STRUCT.unpack(data[record_offset:record_offset + nyan.FRAME_RECORD_STRUCT.size])
            self.assertEqual(record[:3], (0, nyan.MODE_PAL8_RLE, 4))
            self.assertEqual(data[record_offset + nyan.FRAME_RECORD_STRUCT.size:record_offset + nyan.FRAME_RECORD_STRUCT.size + 4],
                             bytes([4, 0, 4, 1]))
            self.assertEqual(struct.unpack("<I", data[palette_offset:palette_offset + 4])[0], 0)
            self.assertEqual(struct.unpack("<I", data[palette_offset + 4:palette_offset + 8])[0], 0x00FFFFFF)


if __name__ == "__main__":
    unittest.main()
