"""Device-shell semantics for the S20+ PMSG warm-reboot marker scripts.

The V1 trial passed 21/21 hostile tests and still failed on the device at the
descriptor-pin check, because every producer fixture executed the generated
script through the host shell. Host `sh` keeps `exec`-opened descriptors across
`exec`; Android's mksh marks descriptors above 2 close-on-exec, so an exec'd
helper cannot see `/proc/self/fd/N`.

The first test is a shape guard that always runs. The rest execute the real
generated bytes through the target's own shell binary under qemu-aarch64, and
are skipped when that private extract or qemu is unavailable.
"""
import importlib.util
import os
from pathlib import Path
import shutil
import subprocess
import unittest

ROOT = Path(__file__).resolve().parents[1]
RUNNER = ROOT / "workspace/public/src/scripts/revalidation/s20plus_g986n_pmsg_warm_reboot_d1.py"
DEVICE_SHELL_ROOT = ROOT / "workspace/private/work/s20plus-twrp-y2q-h0-20260831/ramdisk-stock-iyc2"
DEVICE_SHELL = DEVICE_SHELL_ROOT / "system/bin/sh"
QEMU = shutil.which("qemu-aarch64")

# /dev/zero is a character device on every host that can run this suite, and
# stands in for /dev/pmsg0 so the pin idiom can be exercised without a target.
STAND_IN = "/dev/zero"
STAND_IN_MAJOR = 1
STAND_IN_MINOR = 5


def load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


M = load("_s20_pmsg_shell", RUNNER)


def binding(**overrides):
    value = dict(
        version=M.VERSION,
        source_sha256=M.normalized_source(),
        serial_sha256="11" * 32,
        topology_sha256="22" * 32,
        source_boot_sha256="33" * 32,
        nonce="44" * 32,
        major=STAND_IN_MAJOR,
        minor=STAND_IN_MINOR,
    )
    value.update(overrides)
    return value


def pin_fragment(script):
    """The generated descriptor-pin section, retargeted at the stand-in node."""
    marker = "exec 3< /dev/pmsg0"
    if marker not in script:
        raise AssertionError("generated writer no longer pins a descriptor")
    fragment = script[script.index(marker):]
    return fragment.replace("/dev/pmsg0", STAND_IN)


def for_device_shell(script):
    """Absolute /system paths resolve against the extract, not the host root."""
    return script.replace("/system/bin/", str(DEVICE_SHELL_ROOT / "system" / "bin") + "/")


def for_host_shell(script):
    """The host contrast run uses the host's own coreutils."""
    return script.replace("/system/bin/", "")


def executable_lines(script):
    return [line for line in script.splitlines() if not line.lstrip().startswith("#")]


def run_device_shell(script):
    env = dict(os.environ, QEMU_LD_PREFIX=str(DEVICE_SHELL_ROOT))
    return subprocess.run(
        [QEMU, str(DEVICE_SHELL), "-c", for_device_shell(script)],
        capture_output=True, cwd=str(DEVICE_SHELL_ROOT), env=env, timeout=60,
    )


class ShapeTests(unittest.TestCase):
    def test_generated_scripts_never_address_descriptors_through_proc_self(self):
        # /proc/self names the exec'd helper, not the shell that pinned the
        # descriptor. Every generated reference must go through /proc/$$.
        bound = binding()
        scripts = [M.write_script(bound), M.read_script(bound, "55" * 32)]
        for script in scripts:
            body = "\n".join(executable_lines(script))
            self.assertNotIn("/proc/self/fd/", body)
            self.assertIn("/proc/$$/fd/", body)

    def test_writer_still_pins_before_deriving_the_write_descriptor(self):
        script = M.write_script(binding())
        pin = script.index("exec 3< /dev/pmsg0")
        derive = script.index("exec 4> /proc/$$/fd/3")
        write = script.index("printf '\\n%s\\n'")
        self.assertLess(pin, derive)
        self.assertLess(derive, write)
        # The pathname is never opened with create or truncate.
        self.assertNotIn("> /dev/pmsg0", script)
        self.assertIn("[ ! -L /dev/pmsg0 ] && [ -c /dev/pmsg0 ]", script)


@unittest.skipUnless(QEMU and DEVICE_SHELL.exists(), "qemu-aarch64 or the private stock ramdisk extract is unavailable")
class DeviceShellTests(unittest.TestCase):
    def test_fixture_is_the_targets_own_mksh(self):
        result = run_device_shell('echo "$KSH_VERSION"')
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn(b"MIRBSD KSH", result.stdout)

    def test_generated_pin_and_write_succeed_on_the_device_shell(self):
        fragment = pin_fragment(M.write_script(binding()))
        result = run_device_shell(fragment)
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn(b"S20PMSG_WRITE_V1;returned=1;", result.stdout)
        self.assertEqual(result.stderr, b"")

    def test_proc_self_regression_fails_exactly_as_the_v1_trial_did(self):
        # Reverting to /proc/self must fail here, not on the device. This is
        # the exact failure the consumed V1 trial produced.
        fragment = pin_fragment(M.write_script(binding())).replace("/proc/$$/", "/proc/self/")
        result = run_device_shell(fragment)
        self.assertEqual(result.returncode, 65)
        self.assertNotIn(b"S20PMSG_WRITE_V1", result.stdout)
        self.assertIn(b"/proc/self/fd/3", result.stderr)
        self.assertIn(b"No such file or directory", result.stderr)

    def test_host_shell_cannot_observe_this_difference(self):
        # Why the V1 suite passed: the host shell accepts both shapes, so a
        # host-only fixture constrains nothing about the target.
        fragment = pin_fragment(M.write_script(binding()))
        for script in (fragment, fragment.replace("/proc/$$/", "/proc/self/")):
            result = subprocess.run(["/bin/sh", "-c", for_host_shell(script)], capture_output=True, timeout=30)
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertIn(b"S20PMSG_WRITE_V1;returned=1;", result.stdout)


if __name__ == "__main__":
    unittest.main()
