import json
import struct
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPT_DIR = ROOT / "workspace/public/src/scripts/revalidation"
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

import prepare_video_stream_from_frames_v2902 as frames


def write_pgm(path: Path, width: int, height: int, raster: bytes, *, comment: bool = False) -> None:
    header = f"P5\n{width} {height}\n255\n".encode("ascii")
    if comment:
        header = f"P5\n# generated by unit test\n{width} {height}\n255\n".encode("ascii")
    path.write_bytes(header + raster)


class PrepareVideoStreamFromFramesV2902(unittest.TestCase):
    def test_pgm_sequence_to_mono1_a90vstr(self) -> None:
        with tempfile.TemporaryDirectory(dir=ROOT / "workspace/private/test-runs") as temp:
            root = Path(temp)
            input_dir = root / "frames"
            out_dir = root / "out"
            input_dir.mkdir()
            write_pgm(input_dir / "000001.pgm", 8, 2, bytes([0, 255, 0, 255, 0, 255, 0, 255] * 2), comment=True)
            write_pgm(input_dir / "000002.pgm", 8, 2, bytes([255, 0, 255, 0, 255, 0, 255, 0] * 2))

            result = frames.write_stream_from_frames(
                input_dir=input_dir,
                out_dir=out_dir,
                glob_pattern="*.pgm",
                width=8,
                height=2,
                stride=1,
                fps_num=30,
                fps_den=1,
                input_format="pgm",
                output_format="mono1",
                threshold=128,
                asset_id="unit-pgm-mono1",
            )

            stream = ROOT / result["stream"]
            data = stream.read_bytes()
            self.assertEqual(data[:8], frames.MAGIC)
            header = struct.unpack("<IIIIIIIII32s", data[8:76])
            self.assertEqual(header[:9], (1, 8, 2, 1, frames.PIXEL_FORMAT_MONO1, 30, 1, 2, 2))
            first_record = struct.unpack("<IIQ", data[76:92])
            self.assertEqual(first_record, (0, 2, 0))
            self.assertEqual(data[92:94], b"\x55\x55")
            second_record = struct.unpack("<IIQ", data[94:110])
            self.assertEqual(second_record, (1, 2, 33333333))
            self.assertEqual(data[110:112], b"\xaa\xaa")

            manifest = json.loads((out_dir / "manifest.json").read_text(encoding="utf-8"))
            self.assertEqual(manifest["asset_id"], "unit-pgm-mono1")
            self.assertEqual(manifest["source"]["type"], "host-rendered-frame-sequence")
            self.assertEqual(manifest["source"]["first_frame"], "000001.pgm")
            self.assertEqual(manifest["source"]["last_frame"], "000002.pgm")
            self.assertEqual(manifest["video"]["format"], "mono1")
            self.assertEqual(manifest["video"]["frame_count"], 2)
            self.assertEqual(manifest["video"]["sha256"], result["sha256"])

    def test_raw_gray8_sequence_to_gray8_stream_with_stride_padding(self) -> None:
        with tempfile.TemporaryDirectory(dir=ROOT / "workspace/private/test-runs") as temp:
            root = Path(temp)
            input_dir = root / "frames"
            out_dir = root / "out"
            input_dir.mkdir()
            (input_dir / "frame-001.gray").write_bytes(bytes([1, 2, 3, 4]))

            result = frames.write_stream_from_frames(
                input_dir=input_dir,
                out_dir=out_dir,
                glob_pattern="*.gray",
                width=2,
                height=2,
                stride=4,
                fps_num=24,
                fps_den=1,
                input_format="raw-gray8",
                output_format="gray8",
                threshold=128,
                asset_id="unit-raw-gray8",
            )

            data = (ROOT / result["stream"]).read_bytes()
            header = struct.unpack("<IIIIIIIII32s", data[8:76])
            self.assertEqual(header[:9], (1, 2, 2, 4, frames.PIXEL_FORMAT_GRAY8, 24, 1, 1, 8))
            self.assertEqual(data[92:100], bytes([1, 2, 0, 0, 3, 4, 0, 0]))

    def test_rejects_geometry_mismatch(self) -> None:
        with tempfile.TemporaryDirectory(dir=ROOT / "workspace/private/test-runs") as temp:
            root = Path(temp)
            input_dir = root / "frames"
            input_dir.mkdir()
            write_pgm(input_dir / "000001.pgm", 2, 2, b"\x00\x00\x00\x00")
            with self.assertRaisesRegex(ValueError, "geometry"):
                frames.write_stream_from_frames(
                    input_dir=input_dir,
                    out_dir=root / "out",
                    glob_pattern="*.pgm",
                    width=3,
                    height=2,
                    stride=1,
                    fps_num=30,
                    fps_den=1,
                    input_format="pgm",
                    output_format="mono1",
                    threshold=128,
                )

    def test_pgm_separator_does_not_consume_whitespace_valued_first_pixel(self) -> None:
        with tempfile.TemporaryDirectory(dir=ROOT / "workspace/private/test-runs") as temp:
            path = Path(temp) / "first-pixel-space.pgm"
            path.write_bytes(b"P5\n2 1\n255\n" + bytes([10, 255]))
            raster = frames.read_pgm_p5(path, 2, 1)
            self.assertEqual(raster, bytes([10, 255]))


if __name__ == "__main__":
    unittest.main()
