"""Actual ARM64 command producer at the packaged 100 ms polling cadence.

Real process groups, pipes, socket and packaged BusyBox; kernel/USB are fixtures.
Historical source compositions remain unchanged.
"""
from pathlib import Path
import socket
import shlex
import struct
import subprocess
import tempfile
import time
import unittest
from unittest import mock

import test_s22plus_root_console_v1 as base
import test_s22plus_root_console_arm64 as arm64
import s22plus_native_output_drain_source_v1 as source
import s22plus_native_baseline_protocol_v1 as protocol
import s22plus_root_console_v1 as wire

_original_source=base.source

def producer_source(*,corrected=True):
    value=_original_source()
    identity=source.resident.common.Identity('p998',base.RUN.hex(),'v0.2.2-rc.1')
    helper=(source if corrected else source.previous).helper_template(identity).decode()
    begin=helper.index('#define RC1_RUN_ID_ASCII')
    end=helper.index('/* Return 1 only after authenticated CONTROL ACK',begin)
    start=value.index('#define RC1_RUN_ID_ASCII')
    stop=value.index('static long rc1_console(',start)
    value=value[:start]+helper[begin:end]+'''
static long baseline_check(void){return 0;}
static int baseline_detach_available(void){return 1;}
static void resident_export_current(void){}
'''+value[stop:]
    value=value.replace('static void p282_poll_delay(void){usleep(1000);}',
        'static void p282_poll_delay(void){usleep(100000);}')
    # Fix capacity so the producer exits with >2 seconds of buffered bytes.
    old='static long sys_pipe2(int *fds,int flags){ return neg(pipe2(fds,flags)); }'
    new='''static long sys_pipe2(int *fds,int flags){
 long rc=neg(pipe2(fds,flags));if(rc)return rc;
 if(fcntl(fds[0],F_SETPIPE_SZ,65536)!=65536)_exit(91);return 0;
}'''
    assert value.count(old)==1
    return value.replace(old,new)


class Arm64DrainTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        with mock.patch.object(base,'source',producer_source):
            arm64.Arm64ConsoleTests.setUpClass.__func__(cls)

    setUp=base.ConsoleTests.setUp
    tearDown=base.ConsoleTests.tearDown
    wait=base.ConsoleTests.wait
    output=base.ConsoleTests.output
    finish=base.ConsoleTests.finish

    def burst(self,timeout=15000):
        busybox=shlex.quote(self.launcher[0])+' '+shlex.quote(str(self.folder/'busybox'))
        command=(busybox+' head -c 49152 /dev/zero; printf ERR >&2').encode()
        # Binary data is generated by the actual packaged ARM64 BusyBox.
        seq=self.session.send(wire.EXEC,wire.command(command,timeout_ms=timeout))
        self.wait(wire.ACK,seq)
        return seq,b'\0'*49152

    def test_reaped_buffered_output_survives_two_seconds_and_paused_reader(self):
        seq,wanted=self.burst()
        time.sleep(2.5)
        status=self.session.send(wire.STATUS)
        self.wait(wire.STATUS_REPLY,status)
        end=struct.unpack('<7I',self.wait(wire.EXIT,seq,timeout=14))
        self.assertEqual(end[1:4],(0,0,0))
        self.assertEqual(end[4:6],(len(wanted)+3,0))
        self.assertEqual(self.output(seq,1),wanted)
        self.assertEqual(self.output(seq,2),b'ERR')
        # The short stderr stream must not wait for the stdout backlog.
        kinds=[struct.unpack('<I',b[8:12])[0] for k,n,b in self.events if k==wire.OUTPUT and n==seq]
        self.assertLess(kinds.index(2),len(kinds)-2)
        self.finish()

    def test_original_deadline_still_stops_incomplete_buffered_output(self):
        seq,_=self.burst(timeout=500)
        end=struct.unpack('<7I',self.wait(wire.EXIT,seq,timeout=5))
        self.assertEqual(end[1]&0x8a,0x8a)
        self.assertLess(end[4],49155)
        self.finish()

    def test_cancel_keeps_bounded_incomplete_terminal(self):
        seq,_=self.burst()
        cancel=self.session.send(wire.CANCEL,struct.pack('<I',seq))
        self.wait(wire.ACK,cancel)
        end=struct.unpack('<7I',self.wait(wire.EXIT,seq,timeout=5))
        self.assertEqual(end[1]&0x89,0x89)
        self.finish()

    def test_control_during_output_preserves_honest_terminal(self):
        seq,_=self.burst()
        self.finish()
        end=struct.unpack('<7I',self.wait(wire.EXIT,seq))
        self.assertEqual(end[1]&0xa8,0xa8)
        self.assertLess(end[4],49155)

    def test_background_descendant_is_terminated_and_reaped_before_clean_exit(self):
        busybox=shlex.quote(self.launcher[0])+' '+shlex.quote(str(self.folder/'busybox'))
        command=(busybox+" sh -c 'trap \"\" TERM; while :; do :; done' & printf END").encode()
        seq=self.session.send(wire.EXEC,wire.command(command,timeout_ms=5000))
        end=struct.unpack('<7I',self.wait(wire.EXIT,seq,timeout=5))
        self.assertEqual(end[1:4],(0,0,0));self.assertEqual(self.output(seq,1),b'END')
        self.finish()


class Historical100msTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        with mock.patch.object(base,'source',lambda:producer_source(corrected=False)):
            arm64.Arm64ConsoleTests.setUpClass.__func__(cls)

    setUp=base.ConsoleTests.setUp
    tearDown=base.ConsoleTests.tearDown
    wait=base.ConsoleTests.wait
    output=base.ConsoleTests.output
    finish=base.ConsoleTests.finish
    burst=Arm64DrainTests.burst

    def test_original_composition_reproduces_post_reap_truncation(self):
        seq,_=self.burst()
        end=struct.unpack('<7I',self.wait(wire.EXIT,seq,timeout=5))
        self.assertEqual(end[1],0x88)
        self.assertLess(end[4],49155);self.assertEqual(end[5],0)
        self.finish()


class DetachTests(unittest.TestCase):
    def test_unsettled_group_keeps_two_second_cleanup_stop(self):
        # A controlled unkillable-group result exercises the failure branch;
        # no host process is signalled. Pipe behavior and production tick are real.
        text=producer_source();text=text[:text.index('int main(int argc,char **argv)')]
        old='static long sys_kill(long pid,int sig){ return neg(kill(pid,sig)); }'
        self.assertEqual(text.count(old),1)
        text=text.replace(old,'static long sys_kill(long pid,int sig){(void)pid;(void)sig;return 0;}')
        text+='''
#include <assert.h>
int main(void){
 int p[2];assert(!pipe2(p,O_NONBLOCK|O_CLOEXEC));
 struct rc1_state s={0};s.pid=12345;s.id=3;s.active=1;s.reaped=1;s.exec_seen=1;
 s.timeout=15000;s.command_start=1000;s.cancel_phase=1;s.cancel_start=1000;
 s.pipe[0]=p[0];s.pipe[1]=-1;s.pipe[2]=-1;
 assert(!rc1_child_tick(&s,2999));assert(s.active&&!s.blocked&&!s.terminal_sent);
 assert(!rc1_child_tick(&s,3000));assert(!s.active&&s.blocked&&s.terminal_sent);
 assert(s.flags==(RC1_FLAG_CLEANUP|RC1_FLAG_OUTPUT_INCOMPLETE));
 assert(s.pid==12345&&s.pipe[0]<0);close(p[1]);return 0;
}
'''
        with tempfile.TemporaryDirectory() as folder:
            binary=Path(folder)/'unsettled'
            built=subprocess.run(['cc','-x','c','-','-O2','-Wall','-Wextra','-Werror',
                '-Wno-unused-function','-Wno-misleading-indentation','-o',str(binary)],
                input=text,text=True,capture_output=True,timeout=30)
            self.assertEqual(built.returncode,0,built.stderr)
            subprocess.run([str(binary)],check=True,timeout=3)

    def test_terminal_flags_block_detach_without_any_write_but_nonzero_status_does_not(self):
        for flags,status,dropped in ((0x88,0,0),(1,15,0),(2,15,0),(4,0,1),(0,7<<8,0)):
            with self.subTest(flags=flags),tempfile.TemporaryDirectory() as folder:
                host,peer=socket.socketpair()
                host.setblocking(False);peer.setblocking(False)
                self.addCleanup(host.close);self.addCleanup(peer.close)
                session=protocol.Session(host.fileno(),base.KEY,base.RUN,base.NONCE,Path(folder)/'session')
                self.addCleanup(session.close)
                session.ready=(1,600000,300000,1048576,767,255,0,0)
                session.requests[3]=wire.EXEC;session.request_bodies[3]=wire.command(b'exit 7')
                session.accepted.add(3);session.sequence=4
                session._validate(wire.EXIT,3,struct.pack('<7I',3,flags,status,0,0,dropped,0))
                with mock.patch.object(wire.Session,'send',return_value=4) as send:
                    if flags:
                        with self.assertRaisesRegex(wire.ProtocolError,'complete idle'):
                            session.send(protocol.DETACH)
                        send.assert_not_called()
                    else:
                        self.assertEqual(session.send(protocol.DETACH),4)
                        send.assert_called_once()


if __name__=='__main__':unittest.main()
