/* Generated by a90_wp2_5b_observer_runtime_v1.py; do not edit. */
#ifndef A90_WP2_5B_KMSG_OWNER_V1_H
#define A90_WP2_5B_KMSG_OWNER_V1_H

#include <poll.h>
#include <signal.h>
#include <linux/filter.h>
#include <stddef.h>
#include <stdint.h>
#include <sys/resource.h>
#include <sys/stat.h>
#include <sys/types.h>

#define A90_WP2_5B_OWNER_VERSION 1u
#define A90_WP2_5B_OWNER_PIPE_HEADER_SIZE 24u
#define A90_WP2_5B_OWNER_START_PAYLOAD_SIZE 204u
#define A90_WP2_5B_OWNER_CLOSE_PAYLOAD_SIZE 8u
#define A90_WP2_5B_OWNER_STATUS_PAYLOAD_SIZE 72u
#define A90_WP2_5B_OWNER_MAX_FRAME_SIZE 228u
#define A90_WP2_5B_OWNER_PIPE_ATOMIC_MIN 512u
#define A90_WP2_5B_OWNER_FILTER_CAPACITY 192u

#define A90_WP2_5B_OWNER_DIRECTION_CONTROL 1u
#define A90_WP2_5B_OWNER_DIRECTION_STATUS 2u
#define A90_WP2_5B_OWNER_CONTROL_START 1u
#define A90_WP2_5B_OWNER_CONTROL_CLOSE 2u
#define A90_WP2_5B_OWNER_STATUS_ARMED 1u
#define A90_WP2_5B_OWNER_STATUS_FAULTED 2u
#define A90_WP2_5B_OWNER_STATUS_CLOSED 3u

#define A90_WP2_5B_OWNER_CLOSE_NORMAL 1u
#define A90_WP2_5B_OWNER_CLOSE_FAULT 2u
#define A90_WP2_5B_OWNER_CLOSE_PARENT_EOF 3u

#define A90_WP2_5B_OWNER_CONTROL_FD 3
#define A90_WP2_5B_OWNER_STATUS_FD 4
#define A90_WP2_5B_OWNER_RUN_DIR_FD 5
#define A90_WP2_5B_OWNER_EXEC_FD 6

static const unsigned char a90_wp2_5b_owner_magic[8] = {
    0x41, 0x39, 0x30, 0x4f, 0x33, 0x41, 0x31, 0x00
};
static const unsigned char a90_wp2_5b_owner_contract_sha256[32] = {
    0xc1, 0x87, 0xdd, 0xe1, 0xcb, 0x05, 0x5d, 0x85, 0x37, 0x9f, 0xf6, 0x7a, 0x09, 0x26, 0xaf, 0x09, 0x5b, 0x76, 0x0a, 0x6d, 0x3e, 0xde, 0x78, 0x0b, 0x1a, 0x64, 0x43, 0x5a, 0x04, 0xbd, 0xda, 0x08
};

struct a90_wp2_5b_owner_ops;

struct a90_wp2_5b_owner_confinement {
    int control_fd;
    int status_fd;
    int trace_fd;
    int kmsg_fd;
    uint32_t expected_uid;
    uint32_t expected_gid;
};

struct a90_wp2_5b_owner_ops {
    void *context;
    int (*openat_fn)(void *, int, const char *, int, mode_t);
    int (*close_fn)(void *, int);
    int (*fstat_fn)(void *, int, struct stat *);
    int (*fcntl_fn)(void *, int, int, long);
    off_t (*lseek_fn)(void *, int, off_t, int);
    ssize_t (*read_fn)(void *, int, void *, size_t);
    ssize_t (*write_fn)(void *, int, const void *, size_t);
    int (*poll_fn)(void *, struct pollfd *, nfds_t, int);
    int (*fsync_fn)(void *, int);
    int (*apply_confinement_fn)(void *, const struct a90_wp2_5b_owner_confinement *);
};

struct a90_wp2_5b_owner_result {
    uint32_t fault_reason;
    int32_t os_errno;
    uint32_t poll_revents;
    uint32_t armed;
    uint32_t faulted;
    uint32_t closed;
    uint32_t kmsg_read_calls;
    uint32_t kmsg_reads_after_fault;
    uint64_t trace_dev;
    uint64_t trace_ino;
    uint64_t kmsg_dev;
    uint64_t kmsg_ino;
    uint64_t kmsg_rdev;
    uint64_t durable_trace_bytes;
};

struct a90_wp2_5b_launch_snapshot {
    int sched_other;
    int priority_zero;
    int reset_on_fork;
    int nice_nonnegative;
    unsigned char profile_sha256[32];
    unsigned char affinity_sha256[32];
    unsigned char ioprio_sha256[32];
    unsigned char uclamp_sha256[32];
    unsigned char cgroup_sha256[32];
    unsigned char native_reserve_sha256[32];
    int rlimit_rtprio_zero;
    int rlimit_rttime_positive_bounded;
    int cap_sys_nice_absent;
    int cap_sys_resource_absent;
    int sigchld_blocked;
    int sigchld_default;
    int sigchld_no_cldwait_absent;
    int waiter_reserved;
    int static_elf_fd_validated;
    int clean_mappings;
    int exact_inherited_fd_set;
    int fixed_argv;
    int empty_environment;
    int null_stdio;
    unsigned char root_sha256[32];
    unsigned char cwd_sha256[32];
    unsigned char umask_sha256[32];
    unsigned char credentials_sha256[32];
    unsigned char groups_sha256[32];
    unsigned char rlimits_sha256[32];
    unsigned char capabilities_sha256[32];
    unsigned char signal_mask_sha256[32];
    unsigned char signal_dispositions_sha256[32];
    unsigned char observer_identity_sha256[32];
    unsigned char parent_identity_sha256[32];
    unsigned char executable_sha256[32];
    unsigned char fd_set_sha256[32];
    unsigned char mapping_set_sha256[32];
};

struct a90_wp2_5b_waiter_reservation {
    pid_t pid;
    uint64_t starttime;
    int active;
    int reaped;
};

struct a90_wp2_5b_exec_ops {
    void *context;
    int (*fcntl_fn)(void *, int, int, long);
    int (*execveat_fn)(void *, int, const char *, char *const[], char *const[], int);
};

#ifdef A90_WP2_5B_HOST_TESTING
int a90_wp2_5b_owner_run_with_ops(const struct a90_wp2_5b_owner_ops *ops,
                                  struct a90_wp2_5b_owner_result *result);
#endif
int a90_wp2_5b_owner_run(void);
int a90_wp2_5b_owner_install_confinement(
    const struct a90_wp2_5b_owner_confinement *request);
int a90_wp2_5b_owner_build_filter(
    const struct a90_wp2_5b_owner_confinement *request,
    struct sock_filter *instructions, size_t capacity,
    unsigned short *instruction_count);
int a90_wp2_5b_validate_launch_snapshot(
    const struct a90_wp2_5b_launch_snapshot *snapshot);
int a90_wp2_5b_waiter_reserve(struct a90_wp2_5b_waiter_reservation *reservation,
                              pid_t pid, uint64_t starttime);
int a90_wp2_5b_waiter_generic_reaper_may_reap(
    const struct a90_wp2_5b_waiter_reservation *reservation,
    pid_t pid, uint64_t starttime);
int a90_wp2_5b_waiter_mark_reaped(
    struct a90_wp2_5b_waiter_reservation *reservation,
    pid_t pid, uint64_t starttime);
int a90_wp2_5b_waiter_release(struct a90_wp2_5b_waiter_reservation *reservation);
int a90_wp2_5b_child_exec_transition(const struct a90_wp2_5b_exec_ops *ops);

#endif
