/* Generated by a90_wp2_5b_kmsg_trace_v1.py; do not edit. */
#ifndef A90_WP2_5B_KMSG_CONTRACT_V1_H
#define A90_WP2_5B_KMSG_CONTRACT_V1_H

#include <stddef.h>
#include <stdint.h>

#define A90_WP2_5B_TRACE_VERSION 1u
#define A90_WP2_5B_TRACE_HEADER_SIZE 16u
#define A90_WP2_5B_FRAME_HEADER_SIZE 8u
#define A90_WP2_5B_ARM_PAYLOAD_SIZE 140u
#define A90_WP2_5B_FAULT_PAYLOAD_SIZE 20u
#define A90_WP2_5B_END_PAYLOAD_SIZE 92u
#define A90_WP2_5B_KMSG_RECORD_MAX 8192u
#define A90_WP2_5B_KMSG_PRIORITY_MAX 2047u

#define A90_WP2_5B_FRAME_ARM 1u
#define A90_WP2_5B_FRAME_RECORD 2u
#define A90_WP2_5B_FRAME_FAULT 3u
#define A90_WP2_5B_FRAME_END 4u

#define A90_WP2_5B_FAULT_READ 1u
#define A90_WP2_5B_FAULT_POLL 2u
#define A90_WP2_5B_FAULT_EPIPE 3u
#define A90_WP2_5B_FAULT_EINVAL 4u
#define A90_WP2_5B_FAULT_RECORD_FORMAT 5u
#define A90_WP2_5B_FAULT_SEQUENCE 6u
#define A90_WP2_5B_FAULT_COUNT_CAP 7u
#define A90_WP2_5B_FAULT_BYTE_CAP 8u
#define A90_WP2_5B_FAULT_BOUNDARY 9u

#define A90_WP2_5B_TYPE0_ABSENT "WLAN MAC address is not set, type 0"
#define A90_WP2_5B_TYPE1_ABSENT "WLAN MAC address is not set, type 1"
#define A90_WP2_5B_MAC_TRUE_FAILURE "getting MAC address from platform driver failed"

static const unsigned char a90_wp2_5b_trace_magic[8] = {
    0x41, 0x39, 0x30, 0x4b, 0x35, 0x42, 0x31, 0x00
};
static const unsigned char a90_wp2_5b_contract_sha256[32] = {
    0x54, 0xe9, 0xf8, 0xb7, 0x1d, 0x7b, 0x00, 0xef, 0x4e, 0x4e, 0x96, 0xb7, 0x2b, 0xfe, 0x0b, 0x48, 0x5a, 0xaf, 0x75, 0x59, 0xa9, 0xf5, 0x88, 0x14, 0xf6, 0xa7, 0xab, 0x66, 0x02, 0xc5, 0x93, 0x78
};

typedef int (*a90_wp2_5b_emit_fn)(void *opaque,
                                  const unsigned char *data,
                                  size_t length);

struct a90_wp2_5b_stream {
    a90_wp2_5b_emit_fn emit;
    void *opaque;
    uint32_t record_count_cap;
    uint64_t record_byte_cap;
    uint32_t record_count;
    uint64_t record_bytes;
    uint64_t first_seq;
    uint64_t last_seq;
    int armed;
    int faulted;
    int ended;
};

int a90_wp2_5b_stream_begin(struct a90_wp2_5b_stream *stream,
                            a90_wp2_5b_emit_fn emit,
                            void *opaque,
                            const unsigned char run_binding_sha256[32],
                            const unsigned char qualification_sha256[32],
                            const unsigned char observer_binary_sha256[32],
                            uint32_t record_count_cap,
                            uint64_t record_byte_cap);
int a90_wp2_5b_stream_add_record(struct a90_wp2_5b_stream *stream,
                                 const unsigned char *record,
                                 size_t length);
int a90_wp2_5b_stream_note_fault(struct a90_wp2_5b_stream *stream,
                                 uint32_t reason,
                                 int32_t os_errno,
                                 uint32_t poll_revents);
int a90_wp2_5b_stream_end(
    struct a90_wp2_5b_stream *stream,
    const unsigned char driver_init_epoch_sha256[32],
    const unsigned char capture_close_binding_sha256[32]);

#endif
