#!/bin/sh
### BEGIN INIT INFO
# Provides:          lab-network
# Required-Start:    $local_fs mdev
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Explicitly selected DHCP link
### END INIT INFO
set -eu
test -f /etc/default/lab-network || exit 0
. /etc/default/lab-network
case "${interface:-}" in ''|*[!a-zA-Z0-9_-]*) exit 2 ;; esac
case "$1" in
 start)
  ip link set lo up
  ip link set "$interface" up
  start-stop-daemon --start --oknodo --background --make-pidfile \
    --pidfile /run/lab-dhcp.pid --exec /bin/busybox -- \
    udhcpc -f -i "$interface" -p /run/lab-dhcp.pid -s /usr/local/lib/lab-udhcpc
  ;;
 stop)
  start-stop-daemon --stop --retry TERM/5/KILL/1 --pidfile /run/lab-dhcp.pid || test "$?" = 1
  rm -f /run/lab-dhcp.pid
  ip link set "$interface" down
  ;;
 restart) "$0" stop; "$0" start ;;
 *) exit 2 ;;
esac
